43.用QQ登录到我们的网站/blog/urls.py
from django.urls import path
from . import views

# start with blog
urlpatterns = [
    # http://localhost:8000/blog/
    path('', views.blog_list, name='blog_list'),
    path('<int:blog_pk>', views.blog_detail, name="blog_detail"),
    path('type/<int:blog_type_pk>', views.blogs_with_type, name="blogs_with_type"),
    path('date/<int:year>/<int:month>', views.blogs_with_date, name="blogs_with_date"),
]

43.用QQ登录到我们的网站/user/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('user_info/', views.user_info, name='user_info'),
    path('change_nickname/', views.change_nickname, name='change_nickname'),
    path('bind_email/', views.bind_email, name='bind_email'),
    path('send_verification_code/', views.send_verification_code, name='send_verification_code'),
    path('change_password/', views.change_password, name='change_password'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('login_by_qq', views.login_by_qq, name='login_by_qq'),  # zqyhdm.com/user/login_by_qq
    path('bind_qq', views.bind_qq, name='bind_qq'),
    path('create_user_by_qq', views.create_user_by_qq, name='create_user_by_qq'),
]

43.用QQ登录到我们的网站/user/models.py
from django.db import models 
from django.contrib.auth.models import User


class OAuthRelationship(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    openid = models.CharField(max_length=128)

    OAUTH_TYPE_CHOICES = (
            (0, "QQ"),
            (1, "WeChat"),
            (2, "Sina"),
            (3, "Github"),
        )
    oauth_type = models.IntegerField(default=0, choices=OAUTH_TYPE_CHOICES)

    def __str__(self):
        return "<OAuthRelationship: %s>" % self.user.username

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='昵称')
    nickname = models.CharField(max_length=20)

    def __str__(self):
        return '<Profile: %s for %s>' % (self.nickname, self.user.username)


def get_nickname(self):
    if Profile.objects.filter(user=self).exists():
        profile = Profile.objects.get(user=self)
        return profile.nickname
    else:
        return ''

def get_nickname_or_username(self):
    if Profile.objects.filter(user=self).exists():
        profile = Profile.objects.get(user=self)
        return profile.nickname
    else:
        return '[%s]' % self.username

def has_nickname(self):
    return Profile.objects.filter(user=self).exists()

User.get_nickname = get_nickname
User.get_nickname_or_username = get_nickname_or_username
User.has_nickname = has_nickname

43.用QQ登录到我们的网站/user/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
from .models import OAuthRelationship

class LoginForm(forms.Form):
    username_or_email = forms.CharField(
        label='用户名或邮箱', 
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'请输入用户名或邮箱'})
    )
    password = forms.CharField(label='密码', 
                               widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'请输入密码'}))

    def clean(self):
        username_or_email = self.cleaned_data['username_or_email']
        password = self.cleaned_data['password']

        user = auth.authenticate(username=username_or_email, password=password)
        if user is None:
            if User.objects.filter(email=username_or_email).exists():
                username = User.objects.get(email=username_or_email).username
                user = auth.authenticate(username=username, password=password)
                if not user is None:
                    self.cleaned_data['user'] = user
                    return self.cleaned_data
            raise forms.ValidationError('用户名或密码不正确')
        else:
            self.cleaned_data['user'] = user
        return self.cleaned_data

class RegForm(forms.Form):
    username = forms.CharField(
        label='用户名', 
        max_length=30,
        min_length=3,
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'请输入3-30位用户名'})
    )
    email = forms.EmailField(
        label='邮箱', 
        widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'请输入邮箱'})
    )
    verification_code = forms.CharField(
        label='验证码',
        required=False,
        widget=forms.TextInput(
            attrs={'class':'form-control', 'placeholder':'点击“发送验证码”发送到邮箱'}
        )
    )
    password = forms.CharField(
        label='密码', 
        min_length=6,
        widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'请输入密码'})
    )
    password_again = forms.CharField(
        label='再输入一次密码', 
        min_length=6,
        widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'再输入一次密码'})
    )

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(RegForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断验证码
        code = self.request.session.get('register_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')
        return self.cleaned_data

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('用户名已存在')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('邮箱已存在')
        return email

    def clean_password_again(self):
        password = self.cleaned_data['password']
        password_again = self.cleaned_data['password_again']
        if password != password_again:
            raise forms.ValidationError('两次输入的密码不一致')
        return password_again

    def clean_verification_code(self):
        verification_code = self.cleaned_data.get('verification_code', '').strip()
        if verification_code == '':
            raise forms.ValidationError('验证码不能为空')
        return verification_code

class ChangeNicknameForm(forms.Form):
    nickname_new = forms.CharField(
        label='新的昵称', 
        max_length=20,
        widget=forms.TextInput(
            attrs={'class':'form-control', 'placeholder':'请输入新的昵称'}
        )
    )

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(ChangeNicknameForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登录
        if self.user.is_authenticated:
            self.cleaned_data['user'] = self.user
        else:
            raise forms.ValidationError('用户尚未登录')
        return self.cleaned_data

    def clean_nickname_new(self):
        nickname_new = self.cleaned_data.get('nickname_new', '').strip()
        if nickname_new == '':
            raise forms.ValidationError("新的昵称不能为空")
        return nickname_new

class BindEmailForm(forms.Form):
    email = forms.EmailField(
        label='邮箱',
        widget=forms.EmailInput(
            attrs={'class':'form-control', 'placeholder':'请输入正确的邮箱'}
        )
    )
    verification_code = forms.CharField(
        label='验证码',
        required=False,
        widget=forms.TextInput(
            attrs={'class':'form-control', 'placeholder':'点击“发送验证码”发送到邮箱'}
        )
    )

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(BindEmailForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登录
        if self.request.user.is_authenticated:
            self.cleaned_data['user'] = self.request.user
        else:
            raise forms.ValidationError('用户尚未登录')

        # 判断用户是否已绑定邮箱
        if self.request.user.email != '':
            raise forms.ValidationError('你已经绑定邮箱')

        # 判断验证码
        code = self.request.session.get('bind_email_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')

        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('该邮箱已经被绑定')
        return email

    def clean_verification_code(self):
        verification_code = self.cleaned_data.get('verification_code', '').strip()
        if verification_code == '':
            raise forms.ValidationError('验证码不能为空')
        return verification_code

class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(
        label='旧的密码', 
        widget=forms.PasswordInput(
            attrs={'class':'form-control', 'placeholder':'请输入旧的密码'}
        )
    )
    new_password = forms.CharField(
        label='新的密码', 
        widget=forms.PasswordInput(
            attrs={'class':'form-control', 'placeholder':'请输入新的密码'}
        )
    )
    new_password_again = forms.CharField(
        label='请再次输入新的密码', 
        widget=forms.PasswordInput(
            attrs={'class':'form-control', 'placeholder':'请再次输入新的密码'}
        )
    )

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 验证新的密码是否一致
        new_password = self.cleaned_data.get('new_password', '')
        new_password_again = self.cleaned_data.get('new_password_again', '')
        if new_password != new_password_again or new_password == '':
            raise forms.ValidationError('两次输入的密码不一致')
        return self.cleaned_data

    def clean_old_password(self):
        # 验证旧的密码是否正确
        old_password = self.cleaned_data.get('old_password', '')
        if not self.user.check_password(old_password):
            raise forms.ValidationError('旧的密码错误')
        return old_password

class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(
        label='邮箱',
        widget=forms.EmailInput(
            attrs={'class':'form-control', 'placeholder':'请输入绑定过的邮箱'}
        )
    )
    verification_code = forms.CharField(
        label='验证码',
        required=False,
        widget=forms.TextInput(
            attrs={'class':'form-control', 'placeholder':'点击“发送验证码”发送到邮箱'}
        )
    )
    new_password = forms.CharField(
        label='新的密码', 
        widget=forms.PasswordInput(
            attrs={'class':'form-control', 'placeholder':'请输入新的密码'}
        )
    )

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(ForgotPasswordForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data['email'].strip()
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError('邮箱不存在')
        return email

    def clean_verification_code(self):
        verification_code = self.cleaned_data.get('verification_code', '').strip()
        if verification_code == '':
            raise forms.ValidationError('验证码不能为空')

        # 判断验证码
        code = self.request.session.get('forgot_password_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')

        return verification_code

class BindQQForm(forms.Form):
    username_or_email = forms.CharField(
        label='用户名或邮箱', 
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'请输入用户名或邮箱'})
    )
    password = forms.CharField(label='密码', 
                               widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'请输入密码'}))

    def clean(self):
        username_or_email = self.cleaned_data['username_or_email']
        password = self.cleaned_data['password']

        user = auth.authenticate(username=username_or_email, password=password)
        if user is None:
            if User.objects.filter(email=username_or_email).exists():
                username = User.objects.get(email=username_or_email).username
                user = auth.authenticate(username=username, password=password)
                if not user is None:
                    self.cleaned_data['user'] = user
                    return self.cleaned_data
            raise forms.ValidationError('用户名或密码不正确')

43.用QQ登录到我们的网站/user/templates/user/bind_email.html
{% extends 'form.html' %}

{% block other_buttons %}
    <button id="send_code" class="btn btn-primary">发送验证码</button>
{% endblock %}

{% block script_extends %}
    <script type="text/javascript">
        $("#send_code").click(function(){
            var email = $("#id_email").val();
            if(email==""){
                $("#tip").text('* 邮箱不能为空');
                return false;
            }

            // 发送验证码
            $.ajax({
                url: "{% url 'send_verification_code' %}",
                type: "GET",
                data: {
                    'email': email,
                    'send_for': 'bind_email_code'
                },
                cache: false,
                success: function(data){
                    if(data['status']=='ERROR'){
                        alert(data['status']);    
                    }                    
                }
            });

            // 把按钮变灰
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 30;
            $(this).text(time + 's');
            var interval = setInterval(() => {
                if(time <= 0){
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }

                time --;
                $(this).text(time + 's');
            }, 1000);
        });
    </script>
{% endblock %}

43.用QQ登录到我们的网站/user/templates/user/bind_qq.html
{% extends 'base.html' %}
{% load static %}
{% load user_tags %}

{% block title %}我的网站|绑定用户{% endblock %}
{% block nav_home_active %}active{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if not user.is_authenticated %}
                    <div style="margin: 0 auto; text-align:center;">
                        <img style="border-radius: 50%;" src="{{ avatar }}">
                        <p>你好，{{ nickname }}</p>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">绑定用户</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in bind_qq_form %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span id="tip" class="text-danger">{{ bind_qq_form.non_field_errors }}</span>
                                <div class="clearfix"></div>
                                <a href="{% url 'forgot_password' %}" class="pull-left">忘记密码？</a>
                                <input type="submit" value="绑定" class="btn btn-primary pull-right">
                            </form>
                        </div>
                    </div>
                    <a style="text-align: center; display: block;" href="{% url 'create_user_by_qq' %}?nickname={{ nickname }}">
                        没有账号？直接登录并创建账号 &gt; &gt;
                    </a>
                {% else %}
                    <span>已登录，跳转到首页...</span>
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}              
            </div>
        </div>
    </div>    
{% endblock %}

43.用QQ登录到我们的网站/user/templates/user/forgot_password.html
{% extends 'form.html' %}

{% block other_buttons %}
    <button id="send_code" class="btn btn-primary">发送验证码</button>
{% endblock %}

{% block script_extends %}
    <script type="text/javascript">
        $("#send_code").click(function(){
            var email = $("#id_email").val();
            if(email==""){
                $("#tip").text('* 邮箱不能为空');
                return false;
            }

            // 发送验证码
            $.ajax({
                url: "{% url 'send_verification_code' %}",
                type: "GET",
                data: {
                    'email': email,
                    'send_for': 'forgot_password_code'
                },
                cache: false,
                success: function(data){
                    if(data['status']=='ERROR'){
                        alert(data['status']);    
                    }                    
                }
            });

            // 把按钮变灰
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 30;
            $(this).text(time + 's');
            var interval = setInterval(() => {
                if(time <= 0){
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }

                time --;
                $(this).text(time + 's');
            }, 1000);
        });
    </script>
{% endblock %}

43.用QQ登录到我们的网站/user/templates/user/login.html
{% extends 'base.html' %}
{% load static %}
{% load user_tags %}

{% block title %}我的网站|登录{% endblock %}
{% block nav_home_active %}active{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if not user.is_authenticated %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">登录</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in login_form %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {% if field.id_for_label == 'id_password' %}
                                        （<a href="{% url 'forgot_password' %}" tabindex=-1>忘记密码？</a>）
                                    {% endif %}
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span id="tip" class="text-danger">{{ login_form.non_field_errors }}</span>
                                <div class="clearfix"></div>       
                                <a style="margin-top: 8px; display: inline-block;" href="{% get_login_qq_url %}">
                                    <img src="{% static 'user/qq.png' %}">
                                    使用QQ账号登录
                                </a>                         
                                <input type="submit" value="登录" class="btn btn-primary pull-right">
                            </form>
                        </div>
                    </div>
                    {% if request.GET.from %}
                        <a style="text-align: center; display: block;" href="{% url 'register' %}?from={{ request.GET.from }}">前往注册 &gt;&gt;</a>
                    {% else %}
                        <a style="text-align: center; display: block;" href="{% url 'register' %}?from={{ request.get_full_path }}">前往注册 &gt;&gt;</a>
                    {% endif %}                    
                {% else %}
                    <span>已登录，跳转到首页...</span>
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}              
            </div>
        </div>
    </div>    
{% endblock %}

43.用QQ登录到我们的网站/user/templates/user/register.html
{% extends 'base.html' %}
{% load static %}
{% load user_tags %}

{% block title %}我的网站|注册{% endblock %}
{% block nav_home_active %}active{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if not user.is_authenticated %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">注册</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in reg_form %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {% if field.id_for_label == 'id_email' %}
                                        <div class="input-group">
                                          {{ field }}
                                          <span class="input-group-btn">
                                              <button id="send_code" class="btn btn-default">发送验证码</button>
                                          </span>
                                        </div>
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span id="tip" class="text-danger">{{ reg_form.non_field_errors }}</span>
                                <div class="clearfix"></div>    
                                <a style="margin-top: 8px; display: inline-block;" href="{% get_login_qq_url %}">
                                    <img src="{% static 'user/qq.png' %}">
                                    使用QQ账号登录
                                </a>                             
                                <input type="submit" value="注册" class="btn btn-primary pull-right">
                            </form>
                        </div>
                    </div>    
                    {% if request.GET.from %}
                        <a style="text-align: center; display: block;" href="{% url 'login' %}?from={{ request.GET.from }}">前往登录 &gt;&gt;</a>
                    {% else %}
                        <a style="text-align: center; display: block;" href="{% url 'login' %}?from={{ request.get_full_path }}">前往登录 &gt;&gt;</a>
                    {% endif %}
                    
                {% else %}
                    <span>已登录，跳转到首页...</span>
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}              
            </div>
        </div>
    </div>    
{% endblock %}

{% block script_extends %}
    <script type="text/javascript">
        $("#send_code").click(function(){
            var email = $("#id_email").val();
            if(email==""){
                $("#tip").text('* 邮箱不能为空');
                return false;
            }

            // 发送验证码
            $.ajax({
                url: "{% url 'send_verification_code' %}",
                type: "GET",
                data: {
                    'email': email,
                    'send_for': 'register_code'
                },
                cache: false,
                success: function(data){
                    if(data['status']=='ERROR'){
                        alert(data['status']);    
                    }                    
                }
            });

            // 把按钮变灰
            $(this).addClass('disabled');
            $(this).attr('disabled', true);
            var time = 30;
            $(this).text(time + 's');
            var interval = setInterval(() => {
                if(time <= 0){
                    clearInterval(interval);
                    $(this).removeClass('disabled');
                    $(this).attr('disabled', false);
                    $(this).text('发送验证码');
                    return false;
                }

                time --;
                $(this).text(time + 's');
            }, 1000);
        });
    </script>
{% endblock %}

43.用QQ登录到我们的网站/user/templates/user/user_info.html
{% extends 'base.html' %}

{% block title %}个人资料{% endblock %}
{% block nav_home_active %}active{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                {% if user.is_authenticated %}
                    <h2>{{ user.username }}</h2>
                    <ul>
                        <li>昵称：{{ user.get_nickname }} <a href="{% url 'change_nickname' %}?from={{ request.get_full_path }}">修改昵称</a></li>
                        <li>邮箱：{% if user.email %}{{ user.email }}{% else %}未绑定 <a href="{% url 'bind_email' %}?from={{ request.get_full_path }}">绑定邮箱</a>{% endif %}</li>
                        <li>上一次登录的时间：{{ user.last_login|date:"Y-m-d H:i:s" }}</li>
                        <li><a href="{% url 'change_password' %}">修改密码</a></li>
                    </ul>
                {% else %}
                    <span>未登录，跳转到首页...</span>
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>    
{% endblock %}